# Generated by Django 5.1.3 on 2024-11-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_username_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='user_uploads/default-pfp.jpg', upload_to='user_uploads'),
        ),
    ]
